# Generated by Django 5.2.8 on 2025-11-18 18:56

import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("sensor_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("pressure", models.FloatField()),
                ("status", models.CharField(default="normal", max_length=50)),
            ],
            options={
                "db_table": "sensor_data",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("metric_type", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                ("unit", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "system_metrics",
                "ordering": ["-timestamp"],
            },
        ),
    ]
