# Generated by Django 5.2.8 on 2025-11-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SensorData",
        ),
        migrations.DeleteModel(
            name="SystemMetrics",
        ),
    ]
